model_type: llama3-vision

init_kwargs:
  model_version: "meta-llama/Llama-3.2-11B-Vision-Instruct"
  max_num_frames: 8

generate_kwargs:
  top_p: 1
  top_k: None
  temperature: 0
  max_new_tokens: 1024
