model_type: gpt-4o

init_kwargs:
  model_version: llama-3.1-405b
  max_num_frames: 0
  api_url: https://us.claudeshop.top/v1/chat/completions
  api_key: sk-zfsUvtOALY4YpXG4IRLGNrSRjSuMAtMWKLxV8UlMw7gEclli

generate_kwargs:
  top_p: 1
  top_k: None
  temperature: 0
  max_new_tokens: 1024
