model_type: llava-next

init_kwargs:
  model_version: lmms-lab/llava-onevision-qwen2-7b-ov
  conv_template: qwen_2
  model_name: llava_qwen
  max_num_frames: 8

generate_kwargs:
  top_p: 1
  top_k: None
  temperature: 0
  max_new_tokens: 1024
