model_type: llava-next-video-hf

init_kwargs:
  model_version: llava-hf/LLaVA-NeXT-Video-7B-32K-hf
  max_num_frames: 8

generate_kwargs:
  top_p: 1
  top_k: None
  temperature: 0
  max_new_tokens: 1024
