model_type: longva

init_kwargs:
  model_version: /root/zgp2/fanzheming/LVLM/LongVA-7B
  model_name: llava_qwen
  max_num_frames: 32

generate_kwargs:
  top_p: 1
  top_k: 0
  temperature: 0
  max_new_tokens: 1024
