model_type: vila

init_kwargs:
  model_version: Efficient-Large-Model/Llama-3-LongVILA-8B-128Frames
  max_num_frames: 8
  conv_template: llama_3

generate_kwargs:
  top_p: 1
  top_k: None
  temperature: 0
  max_new_tokens: 1024
