model_type: minicpm-v2.6

init_kwargs:
  model_version: /root/zgp2/fanzheming/LVLM/MiniCPM-o-2_6
  max_num_frames: 8

generate_kwargs:
  top_p: 1
  top_k: None
  temperature: 0
  max_new_tokens: 1024
