model_type: mplug-owl

init_kwargs:
  model_version: /root/zgp2/fanzheming/LVLM/mPLUG-Owl3-7B-241101
  max_num_frames: 8
  attn_implementation: sdpa

generate_kwargs:
  top_p: 1
  top_k: None
  temperature: 0
  max_new_tokens: 1024
