model_type: point-llm

init_kwargs:
  model_version: /mnt/petrelfs/zhoubaichuan/projects/PointLLM/PointLLM-13B-v1.2-ckpt

generate_kwargs:
  top_p: 1
  top_k: None
  temperature: 0
  max_new_tokens: 1024
