model_type: qwen2-vl

init_kwargs:
  model_version: /root/zgp2/fanzheming/LLaMA-Factory/saves/Qwen2-VL-7B-Instruct/lora/trainDVFmc1_2025-04-18-15-37-79/checkpoint-300

generate_kwargs:
  top_p: 1
  top_k: None
  temperature: 0
  max_new_tokens: 2
