model_type: qwen2-vl

init_kwargs:
  model_version: /data/LLaMA-Factory/saves/Qwen2-VL-7B-Instruct-pro1/freeze/train_2025-04-09-14-50-01/checkpoint-2022

generate_kwargs:
  top_p: 1
  top_k: None
  temperature: 0
  max_new_tokens: 2
