model_type: qwen

init_kwargs:
  model_version: qwen-max
  api_url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions

generate_kwargs:
  top_p: 1
  top_k: None
  temperature: 0
  max_new_tokens: 16
